feat: sim replace frontend rpc calls with genlayerjs
yeagerai/genlayer-studio pull request #600
Opened 2024-11-13 03:53 UTC by denishacquin

Fixes #580 

# What

- changed thing a for b
- also did this other unrelated thing in my path

# Why

- to fix a bug
- to add more value to the user

# Testing done

- tested the new feature
- tested the bug fix

# Decisions made

# Checks

- [ ] I have tested this code
- [ ] I have reviewed my own PR
- [ ] I have created an issue for this PR
- [ ] I have set a descriptive PR title compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

# Reviewing tips

# User facing release notes

2024-11-13 03:58 UTC, denishacquin commented
@cristiam86 any hint on how to use **leaderonly** functionality with GenLayer JS?

2024-11-13 14:15 UTC, cristiam86 commented
> @cristiam86 any hint on how to use **leaderonly** functionality with GenLayer JS?

sure, to use it in GenLayerJS, it should be implemented there :D

2024-11-19 07:02 UTC, denishacquin commented
Regarding the **leaderOnly** feature, I've been trying to implement it in genlayer-js, without success until now.

If I dare ask, how important is that feature? Won't it have to be removed once we hook the studio to the real chain? @cristiam86

2024-11-19 08:55 UTC, cristiam86 commented
> Regarding the **leaderOnly** feature, I've been trying to implement it in genlayer-js, without success until now.
> 
> If I dare ask, how important is that feature? Won't it have to be removed once we hook the studio to the real chain? @cristiam86

Let's take a look together whenever you can :) This is going to be available permanently in the localnet. Of course, it won't be available in the testnet or mainnet. 
In Ethereum and other L1s, there are some methods that can be only used in the localnet and they make it easy to force situations or to speed up the development.

2024-11-19 16:21 UTC, denishacquin commented on frontend/src/hooks/useContractQueries.ts
> +    const result = await genlayer.client?.request({
Ah great! I think they weren't there yet when I started this integration! Will update asap!

2024-11-20 04:30 UTC, denishacquin commented
Note that if we want to support the leaderOnly param in this PR, we need to merge the feature in genlayer-js then update the dependency here. @cristiam86

2024-11-28 09:08 UTC, denishacquin commented
I am now having some typing errors between the genvm merge and genlayer-js when fetching contract schema, because the structure we get from the backend doesn't match the type defined in genlayer-js:

```export type ContractSchema = {
  abi: Array<{
    inputs?: Array<{
      name: string;
      type: string;
    }>;
    name?: string;
    outputs?: Array<{
      name: string;
      type: string;
    }>;
    type: "constructor" | "function";
  }>;
  class: string;
};
```
<img width="576" alt="image" src="https://github.com/user-attachments/assets/d33d8ec7-f2b8-4612-bccd-7af4f59b60f2">

2024-11-28 09:10 UTC, cristiam86 commented
we just merged https://github.com/yeagerai/genlayer-studio/pull/653 which changes this as it should be. Backend returns bytes and the frontend decodes it. Now we need to do the same in GenLayerJS

2024-11-28 09:28 UTC, denishacquin commented
> we just merged #653 which changes this as it should be. Backend returns bytes and the frontend decodes it. Now we need to do the same in GenLayerJS

From what I can see that is for eth_call, not for gen_getContractSchema / gen_getContractSchemaForCode

2024-11-28 09:31 UTC, cristiam86 commented
Oh, sure, sorry, my bad.
@kp2pml30 can we go ahead refactoring this in the frontend with the new schema?

2024-11-28 10:38 UTC, denishacquin commented
Ok, then we simply need to update the ContractSchema type in genlayer-js to match the one in the studio.

2024-11-28 10:57 UTC, denishacquin commented
Created an issue  theon genlayer-js side, will take care of it:
https://github.com/yeagerai/genlayer-js/issues/33

2024-11-29 14:26 UTC, cristiam86 requested changes
Great work, but we need to merge this one first: https://github.com/yeagerai/genlayer-js/pull/35 and update the leader_only parameter here.

2024-12-02 08:15 UTC, denishacquin commented
> Great work, but we need to merge this one first: [yeagerai/genlayer-js#35](https://github.com/yeagerai/genlayer-js/pull/35) and update the leader_only parameter here.

Went ahead and merged but turns out we forgot a couple - fixed here: #6 please review @cristiam86 

As soon as it's released in 0.4.6 I'll bump the version here again!

2024-12-04 09:49 UTC, denishacquin reviewed
leader only was updated on both sides

2024-12-04 09:51 UTC, cristiam86 approved these changes

2024-12-04 09:51 UTC, denishacquin reviewed
leader only ok

2024-12-04 09:53 UTC, merged