feat: appeals add validators when appealed
yeagerai/genlayer-studio pull request #603
Opened 2024-11-15 12:12 UTC by kstroobants

Fixes #593

# What

- Implemented issue description
- Refactored consensus flow into state classes and added a transaction_context that contains data that is useful for other states the transaction will go to and it is not in the database. The reason is to perform loops in the consensus with structured code.
- Added class methods to convert dicts to objects. This is needed because an accepted transaction that is appealed needs to be validated by genvm. The genvm accepts only objects (like transaction.consensus_data.leader_receipt.eq_outputs).
- Added tests.

# Why

- To add more value to the user

# Testing done

- Tested the new feature by adding tests to test_base.py
- Simulated it in the simulator

# Checks

- [ ] I have tested this code
- [ ] I have reviewed my own PR
- [ ] I have created an issue for this PR
- [ ] I have set a descriptive PR title compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

# Reviewing tips

Run test_base.py + play around in the simulator.

2024-12-04 11:44 UTC, cristiam86 requested changes
Good job! there are some issues but, in general, it is very good. Please check with @kirilaa if when the transaction enters the appeal process, its process goes to COMMITTING and REVEALING again or if this is processed in a separated flow

2024-12-05 17:20 UTC, kstroobants commented
> Good job! there are some issues but, in general, it is very good. Please check with @kirilaa if when the transaction enters the appeal process, its process goes to COMMITTING and REVEALING again or if this is processed in a separated flow

I checked with him. There is a commit and reveal by the N+2 new validators (that is what the code does).

2024-12-05 17:47 UTC, kstroobants commented on backend/consensus/base.py
> +        ConsensusAlgorithm.dispatch_transaction_status_update(
I moved the transaction database status to the top of the state classes for proposing and committing to be in line with the sol code.

2024-12-05 17:55 UTC, kstroobants commented on backend/consensus/base.py
> +            context.votes[context.validator_nodes[i].address] = (
context.votes = stores the vote from each validator node (= all votes)
single_reveal_votes = creates a dictionary of votes for the current reveal so the rollup transaction contains leader  vote and 1 validator vote (for each validator).

2024-12-05 18:06 UTC, kstroobants commented on backend/consensus/base.py
> +                ConsensusAlgorithm.dispatch_transaction_status_update(
@cristiam86 set_transaction_result() on line 636 will write the consensus data to the transaction in the database. In the pending state the consensus mechanism will know all the validators from that stored consensus data. Then it performs the next states where the consensus data will be overwritten with what currently matters in processing the transaction. 

Why do you want to review it? I see two option:
1. Add the transaction consensus data in a history field in the database, then the frontend (or test print) gets the data from the database.
2. Make a memory in the frontend to keep track of the history.

Lets add this to a new issue?

2024-12-05 18:08 UTC, kstroobants commented on tests/unit/consensus/test_helpers.py
> +                    context = TransactionContext(
Me too. It is not future proof. I'll make an issue to investigate this.

2024-12-05 19:16 UTC, kstroobants commented
@cristiam86: I changed env finality window to 10 seconds, we can change it back to 30min in the future when the user can easily control it. Okay?

2024-12-10 15:29 UTC, cristiam86 commented on backend/consensus/base.py
> +                ConsensusAlgorithm.dispatch_transaction_status_update(
@kstroobants yes please, let's record all the consensus history in the transaction on another issue: https://github.com/yeagerai/genlayer-studio/issues/715

2024-12-10 15:36 UTC, cristiam86 approved these changes

2024-12-11 16:43 UTC, merged