Feat/add rollup consensus service
yeagerai/genlayer-studio pull request #713
Opened 2024-12-10 12:37 UTC by mpaya5

Fixes #671

# What

- Created `/backend/rollup/consensus_service.py` to handle rollup consensus operations
- Added contract deployment persistence in Hardhat environment
- Implemented `deployFixture` in both Hardhat and backend for contract initialization
- Set up Docker volumes for deployment persistence
- Created contract loading functionality in ConsensusService

# Why

- To enable interaction with consensus contracts from the backend
- To ensure contract deployments persist between container restarts
- To maintain consistent contract initialization across environments
- To provide a robust interface for consensus operations

# Testing done

- Verified contract deployment persistence after container restarts
- Tested contract initialization through `deployFixture`
- Verified contract loading in ConsensusService
- Tested file permissions and access in Docker volumes
- Verified contract addresses are correctly loaded from deployment files

# Decisions made

- Implemented `deployFixture` in both environments for flexibility
- Kept the backend's `deploy_fixture` as a fallback option
- Used manual deployment file saving instead of relying on Hardhat's automatic deployment
- Structured ConsensusService to load contracts individually for better error handling

# Checks

- [x] I have tested this code
- [x] I have reviewed my own PR
- [x] I have created an issue for this PR
- [x] I have set a descriptive PR title compliant with conventional commits

# Reviewing tips

- Check the contract initialization order in `deployFixture`
- Verify the contract loading logic in ConsensusService
- Pay attention to the error handling in contract loading
- Review the Docker volume configurations

# User facing release notes

This PR introduces the consensus service backend integration with persistent contract deployments. It enables reliable interaction with consensus contracts and ensures contract deployments persist between system restarts. The service provides a robust interface for consensus operations and maintains consistent contract initialization across environments.

2024-12-10 12:40 UTC, mpaya5 commented
By merging this PR, we can close #670 and #669 as this implementation already includes the persistence functionality that was planned there. 

This PR implements:
- Docker volume mappings for deployments, artifacts and cache
- Manual deployment file saving
- Proper file permissions
- Deployment persistence between container restarts

All the functionality planned for #670 and #669 is covered here as part of the larger consensus service integration.

2024-12-10 12:43 UTC, mpaya5 commented
Closing this PR as the persistence functionality will be implemented as part of #713, which provides a more comprehensive solution including:

- Contract deployment persistence through Docker volumes
- Proper file handling and permissions
- Integration with the consensus service
- Complete deployment workflow

The requirements from this PR will be fully covered there as part of the larger consensus service integration. Please refer to #713 for the implementation.

2024-12-11 20:10 UTC, mpaya5 commented
We need to add more tests for the hardhat deploy functionality and solve the problems related with the Github Actions tests

2024-12-14 22:48 UTC, cristiam86 requested changes

2024-12-14 22:48 UTC, cristiam86 commented on backend/protocol_rpc/endpoints.py
> +from backend.rollup.consensus_service import ConsensusService
@mpaya5 this import is not being used

2024-12-14 22:48 UTC, cristiam86 commented on backend/rollup/consensus_service.py
> +    def _send_transaction(self, contract_function):
@mpaya5 where is this function being used?

2024-12-16 07:21 UTC, mpaya5 commented on backend/protocol_rpc/endpoints.py
> +from backend.rollup.consensus_service import ConsensusService
It's used in the #746

2024-12-16 09:52 UTC, cristiam86 approved these changes

2024-12-16 10:54 UTC, merged