feat: consensus record transaction consensus history in database
yeagerai/genlayer-studio pull request #780
Opened 2024-12-30 10:23 UTC by kstroobants

Fixes #715

# What

- The transaction in the database contains a consensus_history field which is a list of dictionaries. Every time a loop/iteration happens in the consensus mechanism, a dictionary is appended to the database field. This dictionary contains three keys:
  - consensus_round: string explaining the state of the consensus mechanism
  - leader_result: leader receipt if a leader is active (e.g. validator appeal does not contain a leader)
  - validator_results: list of the validator receipts
- The frontend contains shows the history instead of the validators table in the modal. For each dictionary it contains a title (consensus_round) and a table. Each row in the table shows an icon if it is a leader or validator, the leader/validator hash and the vote. The leader is always on the first row.

# Why

- To add more value to the user about the consensus flow.

# Testing done

- Tested the new feature in the localhost.

# Decisions made

The update_consensus_history() function in backend/database_handler/transactions_processor.py could combine leader and validator receipts so that frontend/src/components/Simulator/TransactionItem.vue could be more clear. The split in TransactionItem.vue can be checked in the mode field of the receipt if it is a validator or leader. I did not do this to put the "power" in the backend/consensus/base.py so it is not dependent on future changes in the Receipt data structure.

# Checks

- [ ] I have tested this code
- [ ] I have reviewed my own PR
- [ ] I have created an issue for this PR
- [ ] I have set a descriptive PR title compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

# Reviewing tips

Try the studio. 

f00b6e0d2d710e59f3f3147c1b5a535dacccea66 contains code to go through multiple stage of the consensus by pressing 3 times on the appeal button:
- 5 leader rotations (undetermined)
- Press appeal button
- Leader appeal rotation
- Leader appeal successful
- Press appeal button
- Validator appeal failed
- Press appeal button
- Validator appeal successful
- Accepted (not shown because there is a ConnectionResetError bug thrown by genvm)
![Screenshot 2024-12-30 at 10 08 58](https://github.com/user-attachments/assets/9950ea65-a018-4d9a-90f5-ade20497e3d1)
![Screenshot 2024-12-30 at 10 09 40](https://github.com/user-attachments/assets/9a2bc120-3f56-450b-ab78-b04cf9a45fe4)
![Screenshot 2024-12-30 at 10 09 50](https://github.com/user-attachments/assets/13ec544e-339f-4acb-bfbd-9841c306605e)

# User facing release notes

The transaction details contain the consensus history flow.

2025-02-07 17:17 UTC, cristiam86 commented
@kstroobants the names "Leader appeal" or "Validator appeal" are not correct. Please just put "Appeal"

2025-02-14 15:47 UTC, cristiam86 requested changes
@kstroobants, we also need to record in the consensus_history all the transaction status changes: ACTIVATED, PENDING, PROPOSING, COMMITTING, etc.

2025-02-17 21:49 UTC, kstroobants commented
> @kstroobants, we also need to record in the consensus_history all the transaction status changes: ACTIVATED, PENDING, PROPOSING, COMMITTING, etc.

![Screenshot 2025-02-17 at 21 48 03](https://github.com/user-attachments/assets/19ee5f54-1ed7-43de-aa74-5e84b7c58c13)

2025-02-18 09:07 UTC, cristiam86 approved these changes

2025-02-18 09:55 UTC, merged